### ISSUE TITLE
Infinite loop

### ISSUE THREAD

**Issue by cmjuettner** [Bchir/react-print-tool#2]
When I make a simple call to print a string (or a React component) I get the print preview but it takes a long time and I'm seeing the following error in Chrome dev tools.

<a className="btn btn-link" href="#" onClick={() => {PrintTool.printFromString("<div>Test</div>")}}> <i className="glyphicon glyphicon-print icon-blue xs-mr-8" aria-hidden="true"></i>Print search results</a>

Uncaught Invariant Violation: Maximum update depth exceeded. This can happen when a component repeatedly calls setState inside componentWillUpdate or componentDidUpdate. React limits the number of nested updates to prevent infinite loops.

**Comment by Bchir** [comment]
hello , 
I assure you all components used in this package are stateless. Am not using SetState function you have to check your code, maybe add a code snippet in a comment.

**Comment by cmjuettner** [comment]
Good to know that the package is stateless.  I'll take your advice and tear apart the component that PrintTool is embedded in.  Thanks
