### ISSUE TITLE
自定义的print样式设置无效  是否支持开放属性配置

### ISSUE THREAD

**Issue by leishihong** [Bchir/react-print-tool#3]

**Comment by Bchir** [comment]
@leishihong maybe English  🤔 ?

**Comment by leishihong** [comment]
@Bchir How does my custom css take effect and print style
![image](https://user-images.githubusercontent.com/26375364/75628939-9c54e000-5c18-11ea-8b94-f141ba170a84.png)

printHtml(`.......
<style>
       @media print {
  * {
    -webkit-print-color-adjust: exact;
    -moz-print-color-adjust: exact;
    -ms-print-color-adjust: exact;
    print-color-adjust: exact;
  }
   * {
        padding: 0;
        margin: 0;
      }
      h1,
      h2,
      h3,
      h4,
      h5,
      h6,
      p {
        padding: 0;
        margin: 0;
      }
  body,
  html {
    background-color: #ffffff;
    min-width: auto;
    height: 100%;
    font-size: 20px;
  }
  .print-btn,
  .ant-back-top {
    display: none !important;
  }
  .invoice-box {
    margin-top: 0 !important;
    padding-top: 0 !important;
  }
  .sealHide {
    break-after: page;
    page-break-after: always;
  }

  @page {
     size: A4 landscape;
     margin-bottom: 0;
  }
}
        
    </style>.......... more
`)

**Comment by leishihong** [comment]
@Bchir Looking at the source code, I found that it is not very friendly for the Html elements passed by printHtml, printComponent, etc. or the css style matching included in the React component. It is different from the actual page.How the plugin supports this situation

**Comment by Bchir** [comment]
@leishihong in your case, I guess it will be simpler to use a new tab for printing as it you are trying to print a new HTML document 
```javascript
const printWindow= window.open();
printWindow.document.write(" your HTML doc here");
printWindow.print();
printWindow.close()
```

**Comment by leishihong** [comment]
I want to print silently, the page does not show direct printing, similar to printHtml (), which directly calls the browser to print, but the page is not specifically rendered
@Bchir

**Comment by Bchir** [comment]
what is done here is that the html you put in will be rendered in current document with display none, as far as i know if you want to create an other different document you to create it on a new tab
